CREATE TABLE "profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"profile_created_by" varchar(50),
	"dob" date NOT NULL,
	"marital_status" varchar(50),
	"height" varchar(20),
	"weight" integer,
	"physical_status" varchar(50),
	"gender" varchar(10) NOT NULL,
	"denomination" varchar(100),
	"division" varchar(100),
	"subcaste" varchar(100),
	"mother_tongue" varchar(50),
	"languages_known" jsonb DEFAULT '[]'::jsonb,
	"eating_habits" varchar(50),
	"drinking_habits" varchar(50),
	"smoking_habits" varchar(50),
	"about_me" text,
	"highest_education" varchar(100),
	"college" varchar(255),
	"education_in_detail" text,
	"employed_in" varchar(100),
	"employer" varchar(255),
	"occupation" varchar(100),
	"occupation_in_detail" text,
	"annual_income" varchar(50),
	"family_value" varchar(50),
	"family_type" varchar(50),
	"family_status" varchar(50),
	"native_place" varchar(255),
	"religious_values" varchar(50),
	"parents_marital_status" varchar(50),
	"father_name" varchar(100),
	"father_occupation" varchar(100),
	"mother_name" varchar(100),
	"mother_occupation" varchar(100),
	"brothers_count" integer DEFAULT 0,
	"sisters_count" integer DEFAULT 0,
	"about_family" text,
	"hobbies" jsonb DEFAULT '[]'::jsonb,
	"interests" jsonb DEFAULT '[]'::jsonb,
	"music" jsonb DEFAULT '[]'::jsonb,
	"sports" jsonb DEFAULT '[]'::jsonb,
	"food" jsonb DEFAULT '[]'::jsonb,
	"country" varchar(100),
	"state" varchar(100),
	"city" varchar(100),
	"citizenship" varchar(100),
	"contact_email" varchar(255),
	"contact_mobile" varchar(15),
	"whatsapp" varchar(15),
	"instagram" varchar(255),
	"linkedin" varchar(255),
	"x" varchar(255),
	"profile_image" varchar(500),
	"gallery_images" jsonb DEFAULT '[]'::jsonb,
	"profile_completion" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"is_verified" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "profiles_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(100) NOT NULL,
	"mobile" varchar(15),
	"password_hash" varchar(255) NOT NULL,
	"email_verified" boolean DEFAULT false,
	"last_active_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;